PINECONE_API_KEY = "pcsk_35CVYt_MpRPqBmbf5b1888vkB9V2mC6Yfp3dGoCSRSe5THG92Veeow5AE2XGxS6wKevvQh"
DEEPSEEK_API_KEY = "sk-731c12e889f7435da417d60b8be33f78"
DEEPSEEK_BASE_URL = "https://api.deepseek.com/v1"
INDEX_NAME = "erp-embeddings"
DIMENSION = 384
